{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cielo.lio",
    "module": "order-manager",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "zxlnu242gvd5rik3afjssx6uci"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "order-manager-2.0.1.aar",
          "url": "order-manager-2.0.1.aar",
          "size": 219987,
          "sha512": "dd9bd3e52470343ffb2f4d0b64211f335a7865a9ddacbb1d8e24b3cd4618c7719510f213c97aea4fb7bf021cbf31a5128f32d12bd15bc204ee906a9ba776e53d",
          "sha256": "f97479ab76aaf5e5c62dbaa8859b25f7a166a6b7e924854dd7b417dafba4ce5e",
          "sha1": "6e160bcd0e40ea94ea1865b6f40c15b8e39c8308",
          "md5": "7dd8f897831d8310ec2f1c93c3cf6523"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-analytics",
          "version": {
            "requires": "18.0.3"
          }
        },
        {
          "group": "com.datadoghq",
          "module": "dd-sdk-android",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "order-manager-2.0.1.aar",
          "url": "order-manager-2.0.1.aar",
          "size": 219987,
          "sha512": "dd9bd3e52470343ffb2f4d0b64211f335a7865a9ddacbb1d8e24b3cd4618c7719510f213c97aea4fb7bf021cbf31a5128f32d12bd15bc204ee906a9ba776e53d",
          "sha256": "f97479ab76aaf5e5c62dbaa8859b25f7a166a6b7e924854dd7b417dafba4ce5e",
          "sha1": "6e160bcd0e40ea94ea1865b6f40c15b8e39c8308",
          "md5": "7dd8f897831d8310ec2f1c93c3cf6523"
        }
      ]
    }
  ]
}
